version: "3.7"
services:
    app:
        image: inkwo/twdo-backend
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file: .env
        container_name: twdo-backend
        depends_on:
            - twdo-db
        links:
            - twdo-db
        volumes:
            - .:/home/node/twdo-backend
            - /home/node/twdo-backend/node_modules
            - ./files:/home/node/twdo-backend/files
        ports:
            - "4001:4001"

    twdo-db:
        image: postgres:11.12
        container_name: twdo-db
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: twdo-db
        volumes:
            - twdodata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
volumes:
    twdodata:
        driver: local
